# Generated by Django 4.2.15 on 2026-05-18 22:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicalNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('note_type', models.CharField(default='EVOLUCION', max_length=40)),
                ('content', models.TextField()),
                ('status', models.CharField(choices=[('BORRADOR', 'Borrador'), ('FIRMADA', 'Firmada'), ('ANULADA', 'Anulada')], default='BORRADOR', max_length=20)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('content_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('signature_blob', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('icd10_code', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=255)),
                ('diagnosis_type', models.CharField(choices=[('PRINCIPAL', 'Principal'), ('SECUNDARIO', 'Secundario'), ('COMORBILIDAD', 'Comorbilidad')], default='PRINCIPAL', max_length=20)),
                ('is_primary', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('ACTIVO', 'Activo'), ('RESUELTO', 'Resuelto'), ('CANCELADO', 'Cancelado')], default='ACTIVO', max_length=20)),
                ('recorded_at', models.DateTimeField(auto_now_add=True, db_column='recorded_at')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('medication_name', models.CharField(max_length=255)),
                ('medication_code', models.CharField(blank=True, max_length=60, null=True)),
                ('dose', models.CharField(max_length=80)),
                ('frequency', models.CharField(max_length=120)),
                ('route', models.CharField(choices=[('ORAL', 'Oral'), ('IV', 'Intravenoso'), ('IM', 'Intramuscular'), ('TOPICA', 'Tópica'), ('INHALADA', 'Inhalada'), ('NASAL', 'Nasal'), ('OTICO', 'Ótico'), ('OCULAR', 'Ocular')], max_length=30)),
                ('duration_days', models.IntegerField(blank=True, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('instructions', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVA', 'Activa'), ('SUSPENDIDA', 'Suspendida'), ('COMPLETADA', 'Completada'), ('CANCELADA', 'Cancelada')], default='ACTIVA', max_length=20)),
                ('prescribed_at', models.DateTimeField(auto_now_add=True, db_column='prescribed_at')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-prescribed_at'],
            },
        ),
    ]
