# Generated by Django 4.2.15 on 2026-04-26 16:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('doctors', '0001_initial'),
        ('clinical', '0001_initial'),
        ('encounters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='encounter',
            field=models.ForeignKey(db_column='encounter_id', on_delete=django.db.models.deletion.CASCADE, to='encounters.encounter'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='prescribed_by',
            field=models.ForeignKey(db_column='prescribed_by', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='encounter',
            field=models.ForeignKey(db_column='encounter_id', on_delete=django.db.models.deletion.CASCADE, to='encounters.encounter'),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='recorded_by',
            field=models.ForeignKey(db_column='recorded_by', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clinicalnote',
            name='created_by',
            field=models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.PROTECT, related_name='clinical_notes_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clinicalnote',
            name='doctor',
            field=models.ForeignKey(db_column='doctor_id', on_delete=django.db.models.deletion.PROTECT, to='doctors.doctor'),
        ),
        migrations.AddField(
            model_name='clinicalnote',
            name='encounter',
            field=models.ForeignKey(db_column='encounter_id', on_delete=django.db.models.deletion.CASCADE, to='encounters.encounter'),
        ),
        migrations.AddField(
            model_name='clinicalnote',
            name='signed_by',
            field=models.ForeignKey(blank=True, db_column='signed_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clinical_notes_signed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clinicalnote',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clinical_notes_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['encounter', 'prescribed_at'], name='rx_encounter_idx'),
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['status'], name='rx_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='prescription',
            constraint=models.CheckConstraint(check=models.Q(('status__in', ['ACTIVA', 'SUSPENDIDA', 'COMPLETADA', 'CANCELADA'])), name='rx_status_check'),
        ),
        migrations.AddConstraint(
            model_name='prescription',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('duration_days__isnull', True), ('duration_days__gt', 0), _connector='OR')), name='rx_duration_check'),
        ),
        migrations.AddIndex(
            model_name='diagnosis',
            index=models.Index(fields=['encounter'], name='diag_encounter_idx'),
        ),
        migrations.AddIndex(
            model_name='diagnosis',
            index=models.Index(fields=['icd10_code'], name='diag_icd10_idx'),
        ),
        migrations.AddIndex(
            model_name='diagnosis',
            index=models.Index(fields=['status'], name='diag_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='diagnosis',
            constraint=models.CheckConstraint(check=models.Q(('diagnosis_type__in', ['PRINCIPAL', 'SECUNDARIO', 'COMORBILIDAD'])), name='diag_type_check'),
        ),
        migrations.AddConstraint(
            model_name='diagnosis',
            constraint=models.CheckConstraint(check=models.Q(('status__in', ['ACTIVO', 'RESUELTO', 'CANCELADO'])), name='diag_status_check'),
        ),
        migrations.AddIndex(
            model_name='clinicalnote',
            index=models.Index(fields=['encounter', 'created_at'], name='note_encounter_idx'),
        ),
        migrations.AddIndex(
            model_name='clinicalnote',
            index=models.Index(fields=['doctor', 'created_at'], name='note_doctor_idx'),
        ),
        migrations.AddIndex(
            model_name='clinicalnote',
            index=models.Index(fields=['status'], name='note_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='clinicalnote',
            constraint=models.CheckConstraint(check=models.Q(('status__in', ['BORRADOR', 'FIRMADA', 'ANULADA'])), name='note_status_check'),
        ),
        migrations.AddConstraint(
            model_name='clinicalnote',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('signed_at__isnull', False), ('signed_by__isnull', False), ('status', 'FIRMADA')), models.Q(('status', 'FIRMADA'), _negated=True), _connector='OR'), name='note_signed_check'),
        ),
    ]
