# Generated by Django 4.2.15 on 2026-05-18 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=120, unique=True)),
                ('module', models.CharField(max_length=60)),
                ('resource', models.CharField(max_length=80)),
                ('action', models.CharField(max_length=40)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['id'],
                'indexes': [models.Index(fields=['module'], name='perm_module_idx'), models.Index(fields=['resource', 'action'], name='perm_res_action_idx')],
            },
        ),
    ]
