# Generated by Django 3.2.25 on 2026-05-11 22:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core_organizations', '0002_convert_org_id_to_uuid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('doctors', '0002_convert_org_to_uuid'),
        ('patients', '0002_convert_org_to_uuid'),
        ('encounters', '0002_convert_org_to_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('order_number', models.CharField(max_length=50)),
                ('priority', models.CharField(choices=[('NORMAL', 'Normal'), ('URGENTE', 'Urgente')], default='NORMAL', max_length=20)),
                ('status', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('RECOLECTADA', 'Recolectada'), ('EN_PROCESO', 'En proceso'), ('COMPLETADA', 'Completada'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=20)),
                ('ordered_at', models.DateTimeField(auto_now_add=True, db_column='ordered_at')),
                ('expected_collection_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.PROTECT, related_name='lab_orders_created', to=settings.AUTH_USER_MODEL)),
                ('doctor', models.ForeignKey(db_column='doctor_id', on_delete=django.db.models.deletion.PROTECT, to='doctors.doctor')),
                ('encounter', models.ForeignKey(db_column='encounter_id', on_delete=django.db.models.deletion.PROTECT, to='encounters.encounter')),
                ('organization', models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.PROTECT, to='core_organizations.organization')),
                ('patient', models.ForeignKey(db_column='patient_id', on_delete=django.db.models.deletion.PROTECT, to='patients.patient')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lab_orders_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-ordered_at'],
            },
        ),
        migrations.CreateModel(
            name='LabOrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDIENTE', 'Pendiente')], default='PENDIENTE', max_length=20)),
                ('lab_order', models.ForeignKey(db_column='lab_order_id', on_delete=django.db.models.deletion.CASCADE, to='lab.laborder')),
            ],
        ),
        migrations.CreateModel(
            name='LabTestCatalog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('sample_type', models.CharField(max_length=40)),
                ('unit', models.CharField(blank=True, max_length=30, null=True)),
                ('reference_min', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('reference_max', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='LabResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('result_text', models.CharField(blank=True, max_length=255, null=True)),
                ('result_numeric', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('unit', models.CharField(blank=True, max_length=30, null=True)),
                ('ref_min', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('ref_max', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('result_flag', models.CharField(choices=[('NORMAL', 'Normal'), ('ANORMAL', 'Anormal'), ('CRITICO', 'Crítico')], default='NORMAL', max_length=20)),
                ('processed_at', models.DateTimeField(auto_now_add=True, db_column='processed_at')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('lab_order_item', models.ForeignKey(db_column='lab_order_item_id', on_delete=django.db.models.deletion.CASCADE, to='lab.laborderitem')),
                ('processed_by', models.ForeignKey(db_column='processed_by', on_delete=django.db.models.deletion.PROTECT, related_name='lab_results_processed', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, db_column='reviewed_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_results_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-processed_at'],
            },
        ),
        migrations.AddField(
            model_name='laborderitem',
            name='lab_test',
            field=models.ForeignKey(db_column='lab_test_id', on_delete=django.db.models.deletion.PROTECT, to='lab.labtestcatalog'),
        ),
        migrations.AddIndex(
            model_name='labresult',
            index=models.Index(fields=['lab_order_item'], name='lab_result_item_idx'),
        ),
        migrations.AddIndex(
            model_name='labresult',
            index=models.Index(fields=['processed_at'], name='lab_result_processed_idx'),
        ),
        migrations.AddIndex(
            model_name='labresult',
            index=models.Index(fields=['result_flag'], name='lab_result_flag_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='laborderitem',
            unique_together={('lab_order', 'lab_test')},
        ),
        migrations.AddIndex(
            model_name='laborder',
            index=models.Index(fields=['encounter'], name='lab_order_encounter_idx'),
        ),
        migrations.AddIndex(
            model_name='laborder',
            index=models.Index(fields=['patient'], name='lab_order_patient_idx'),
        ),
        migrations.AddIndex(
            model_name='laborder',
            index=models.Index(fields=['status'], name='lab_order_status_idx'),
        ),
        migrations.AddIndex(
            model_name='laborder',
            index=models.Index(fields=['ordered_at'], name='lab_order_ordered_at_idx'),
        ),
        migrations.AddConstraint(
            model_name='laborder',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('organization', 'order_number'), name='lab_order_org_number_unique'),
        ),
        migrations.AddConstraint(
            model_name='laborder',
            constraint=models.CheckConstraint(check=models.Q(('priority__in', ['NORMAL', 'URGENTE'])), name='lab_order_priority_check'),
        ),
        migrations.AddConstraint(
            model_name='laborder',
            constraint=models.CheckConstraint(check=models.Q(('status__in', ['PENDIENTE', 'RECOLECTADA', 'EN_PROCESO', 'COMPLETADA', 'CANCELADA'])), name='lab_order_status_check'),
        ),
    ]
