[pytest]
DJANGO_SETTINGS_MODULE = config.settings_docker
python_files = test*.py *_test.py tests/**/*.py
testpaths = accounts appointments apps core doctors patients clinical encounters lab imaging medical_records personnel utils
addopts = -v --tb=short
