# Generated by Django 4.2.15 on 2026-05-18 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core_organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_type', models.CharField(max_length=80)),
                ('resource_id', models.UUIDField()),
                ('access_type', models.CharField(max_length=40)),
                ('granted', models.BooleanField(default=True)),
                ('denied_reason', models.TextField(blank=True, null=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.PROTECT, to='core_organizations.organization')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
