# Generated by Django 4.2.15 on 2026-04-26 16:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core_organizations', '0001_initial'),
        ('core_users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_type', models.CharField(max_length=80)),
                ('resource_id', models.UUIDField()),
                ('access_type', models.CharField(max_length=40)),
                ('granted', models.BooleanField(default=True)),
                ('denied_reason', models.TextField(blank=True, null=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.PROTECT, to='core_organizations.organization')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [
                    models.Index(fields=['organization', 'created_at'], name='access_org_created_idx'),
                    models.Index(fields=['resource_type', 'resource_id', 'created_at'], name='access_resource_idx'),
                    models.Index(fields=['user', 'created_at'], name='access_user_created_idx'),
                ],
            },
        ),
    ]
