# Generated by Django 4.2.15 on 2026-04-26 16:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('start_at', models.DateTimeField(db_column='start_at')),
                ('end_at', models.DateTimeField(db_column='end_at')),
                ('appointment_type', models.CharField(choices=[('CONSULTA', 'Consulta General'), ('CONTROL', 'Control Médico'), ('EMERGENCIA', 'Emergencia'), ('SEGUIMIENTO', 'Seguimiento')], default='CONSULTA', max_length=40)),
                ('reason', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PROGRAMADA', 'Programada'), ('CONFIRMADA', 'Confirmada'), ('EN_CURSO', 'En curso'), ('COMPLETADA', 'Completada'), ('CANCELADA', 'Cancelada'), ('NO_ASISTIO', 'No asistió')], default='PROGRAMADA', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['start_at'],
            },
        ),
    ]
