# Generated by Django 4.2.15 on 2026-04-26 16:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('doctors', '0001_initial'),
        ('appointments', '0001_initial'),
        ('core_organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='appointments_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(db_column='doctor_id', on_delete=django.db.models.deletion.PROTECT, to='doctors.doctor'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='organization_id',
            field=models.UUIDField(db_column='organization_id'),
        ),
        migrations.RunSQL(
            sql=[
                "ALTER TABLE appointments_appointment ADD CONSTRAINT appointments_appointment_org_fk FOREIGN KEY (organization_id) REFERENCES core_organizations_organization(id)",
            ],
            reverse_sql=[
                "ALTER TABLE appointments_appointment DROP CONSTRAINT IF EXISTS appointments_appointment_org_fk",
            ],
        ),
        migrations.AddField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(db_column='patient_id', on_delete=django.db.models.deletion.PROTECT, to='patients.patient'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='appointments_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['doctor', 'start_at'], name='appt_doctor_start_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['patient', 'start_at'], name='appt_patient_start_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['status'], name='appt_status_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['deleted_at'], name='appt_deleted_at_idx'),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.CheckConstraint(check=models.Q(('end_at__gt', models.F('start_at'))), name='appt_end_after_start_check'),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.CheckConstraint(check=models.Q(('status__in', ['PROGRAMADA', 'CONFIRMADA', 'EN_CURSO', 'COMPLETADA', 'CANCELADA', 'NO_ASISTIO'])), name='appt_status_check'),
        ),
    ]
