# Generated by Django 4.2.15 on 2026-04-26 16:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0002_initial'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('doctors', '0001_initial'),
        ('core_organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Encounter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('encounter_type', models.CharField(choices=[('AMBULATORIO', 'Ambulatorio'), ('INTERNAMIENTO', 'Internamiento'), ('EMERGENCIA', 'Emergencia'), ('TELECONSULTA', 'Teleconsulta')], max_length=20)),
                ('status', models.CharField(choices=[('ABIERTO', 'Abierto'), ('CERRADO', 'Cerrado'), ('CANCELADO', 'Cancelado')], default='ABIERTO', max_length=20)),
                ('start_at', models.DateTimeField(db_column='start_at')),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('chief_complaint', models.TextField(blank=True, null=True)),
                ('room_number', models.CharField(blank=True, max_length=40, null=True)),
                ('bed_number', models.CharField(blank=True, max_length=40, null=True)),
                ('admission_source', models.CharField(blank=True, max_length=80, null=True)),
                ('discharge_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('appointment', models.ForeignKey(blank=True, db_column='appointment_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='appointments.appointment')),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='encounters_created', to=settings.AUTH_USER_MODEL)),
                ('doctor', models.ForeignKey(db_column='doctor_id', on_delete=django.db.models.deletion.PROTECT, to='doctors.doctor')),
                ('organization', models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.PROTECT, to='core_organizations.organization')),
                ('patient', models.ForeignKey(db_column='patient_id', on_delete=django.db.models.deletion.PROTECT, to='patients.patient')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='encounters_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['start_at'],
            },
        ),
        migrations.RunSQL(
            sql=[
                "ALTER TABLE encounters_encounter ADD CONSTRAINT encounters_encounter_org_fk FOREIGN KEY (organization_id) REFERENCES core_organizations_organization(id)",
            ],
            reverse_sql=[
                "ALTER TABLE encounters_encounter DROP CONSTRAINT IF EXISTS encounters_encounter_org_fk",
            ],
        ),
        migrations.CreateModel(
            name='VitalSign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('recorded_at', models.DateTimeField(auto_now_add=True, db_column='recorded_at')),
                ('temperature_c', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('bp_systolic', models.IntegerField(blank=True, null=True)),
                ('bp_diastolic', models.IntegerField(blank=True, null=True)),
                ('heart_rate', models.IntegerField(blank=True, null=True)),
                ('respiratory_rate', models.IntegerField(blank=True, null=True)),
                ('oxygen_saturation', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('height_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('bmi', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('glucose_mg_dl', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('encounter', models.ForeignKey(db_column='encounter_id', on_delete=django.db.models.deletion.CASCADE, to='encounters.encounter')),
                ('recorded_by', models.ForeignKey(db_column='recorded_by', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['encounter', 'recorded_at'], name='vitals_encounter_idx'), models.Index(fields=['recorded_by'], name='vitals_recorded_by_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='encounter',
            index=models.Index(fields=['patient', 'start_at'], name='enc_patient_start_idx'),
        ),
        migrations.AddIndex(
            model_name='encounter',
            index=models.Index(fields=['doctor', 'start_at'], name='enc_doctor_start_idx'),
        ),
        migrations.AddIndex(
            model_name='encounter',
            index=models.Index(fields=['status'], name='enc_status_idx'),
        ),
        migrations.AddIndex(
            model_name='encounter',
            index=models.Index(fields=['encounter_type'], name='enc_type_idx'),
        ),
        migrations.AddConstraint(
            model_name='encounter',
            constraint=models.CheckConstraint(check=models.Q(('encounter_type__in', ['AMBULATORIO', 'INTERNAMIENTO', 'EMERGENCIA', 'TELECONSULTA'])), name='enc_type_check'),
        ),
        migrations.AddConstraint(
            model_name='encounter',
            constraint=models.CheckConstraint(check=models.Q(('status__in', ['ABIERTO', 'CERRADO', 'CANCELADO'])), name='enc_status_check'),
        ),
        migrations.AddConstraint(
            model_name='encounter',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('end_at__isnull', True), ('end_at__gt', models.F('start_at')), _connector='OR')), name='enc_end_after_start_check'),
        ),
    ]
