# Generated by Django 3.2.25 on 2026-05-11 22:28

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('encounters', '0002_convert_org_to_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('CONSULTA', 'Consulta'), ('PROCEDIMIENTO', 'Procedimiento'), ('LAB', 'Laboratorio'), ('IMAGEN', 'Imagen'), ('INTERNAMIENTO', 'Internamiento')], max_length=40)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('ars_code', models.CharField(blank=True, max_length=60, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='EncounterBilling',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('ncf_number', models.CharField(blank=True, max_length=50, null=True)),
                ('ars_provider', models.CharField(blank=True, max_length=120, null=True)),
                ('ars_affiliation_number', models.CharField(blank=True, max_length=60, null=True)),
                ('billing_status', models.CharField(choices=[('PENDIENTE', 'Pendiente')], default='PENDIENTE', max_length=20)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('billed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('encounter', models.ForeignKey(db_column='encounter_id', on_delete=django.db.models.deletion.PROTECT, to='encounters.encounter')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='encounterbilling',
            index=models.Index(fields=['encounter'], name='billing_encounter_idx'),
        ),
        migrations.AddIndex(
            model_name='encounterbilling',
            index=models.Index(fields=['billing_status'], name='billing_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='encounterbilling',
            constraint=models.UniqueConstraint(condition=models.Q(('ncf_number__isnull', False)), fields=('ncf_number',), name='billing_ncf_unique'),
        ),
    ]
