# Generated by Django 4.2.15 on 2026-05-18 22:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=160)),
                ('trade_name', models.CharField(blank=True, max_length=160, null=True)),
                ('rnc', models.CharField(blank=True, max_length=20, null=True)),
                ('phone', models.CharField(blank=True, max_length=25, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('province', models.CharField(blank=True, max_length=120, null=True)),
                ('municipality', models.CharField(blank=True, max_length=120, null=True)),
                ('timezone', models.CharField(default='America/Santo_Domingo', max_length=64)),
                ('language_code', models.CharField(default='es-DO', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['id'],
                'indexes': [models.Index(fields=['is_active'], name='org_is_active_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='organization',
            constraint=models.UniqueConstraint(condition=models.Q(('rnc__isnull', False)), fields=('rnc',), name='org_rnc_unique'),
        ),
    ]
