# Generated by Django 4.2.15 on 2026-05-18 22:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core_organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('identity_type', models.CharField(choices=[('CEDULA', 'Cédula'), ('PASAPORTE', 'Pasaporte'), ('OTRO', 'Otro')], default='CEDULA', max_length=20)),
                ('cedula', models.CharField(blank=True, max_length=20, null=True)),
                ('passport_number', models.CharField(blank=True, max_length=40, null=True)),
                ('first_name', models.CharField(max_length=120)),
                ('last_name', models.CharField(max_length=120)),
                ('birth_date', models.DateField()),
                ('sex', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=1)),
                ('nationality', models.CharField(default='DOMINICANA', max_length=80)),
                ('phone_primary', models.CharField(blank=True, max_length=25, null=True)),
                ('phone_secondary', models.CharField(blank=True, max_length=25, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('province', models.CharField(blank=True, max_length=120, null=True)),
                ('municipality', models.CharField(blank=True, max_length=120, null=True)),
                ('blood_type', models.CharField(blank=True, max_length=5, null=True)),
                ('allergies', models.TextField(blank=True, null=True)),
                ('chronic_conditions', models.TextField(blank=True, null=True)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=150, null=True)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=25, null=True)),
                ('emergency_contact_relation', models.CharField(blank=True, max_length=60, null=True)),
                ('ars_provider', models.CharField(blank=True, max_length=120, null=True)),
                ('ars_affiliation_number', models.CharField(blank=True, max_length=60, null=True)),
                ('status', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo'), ('FALLECIDO', 'Fallecido')], default='ACTIVO', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='patients_created', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.PROTECT, to='core_organizations.organization')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='patients_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
                'indexes': [models.Index(fields=['organization'], name='patient_org_idx'), models.Index(fields=['last_name', 'first_name'], name='patient_name_idx'), models.Index(fields=['phone_primary'], name='patient_phone_idx'), models.Index(fields=['deleted_at'], name='patient_deleted_at_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='patient',
            constraint=models.CheckConstraint(check=models.Q(('sex__in', ['M', 'F', 'O'])), name='patient_sex_check'),
        ),
        migrations.AddConstraint(
            model_name='patient',
            constraint=models.CheckConstraint(check=models.Q(('identity_type__in', ['CEDULA', 'PASAPORTE', 'OTRO'])), name='patient_identity_type_check'),
        ),
        migrations.AddConstraint(
            model_name='patient',
            constraint=models.CheckConstraint(check=models.Q(('status__in', ['ACTIVO', 'INACTIVO', 'FALLECIDO'])), name='patient_status_check'),
        ),
        migrations.AddConstraint(
            model_name='patient',
            constraint=models.UniqueConstraint(fields=('organization', 'cedula'), name='patient_org_cedula_unique'),
        ),
        migrations.AddConstraint(
            model_name='patient',
            constraint=models.UniqueConstraint(fields=('organization', 'passport_number'), name='patient_org_passport_unique'),
        ),
    ]
