# Generated by Django 4.2.15 on 2026-04-26 16:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core_organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['id'],
                'indexes': [models.Index(fields=['is_active'], name='specialty_is_active_idx')],
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('cedula', models.CharField(max_length=20)),
                ('license_number', models.CharField(max_length=60)),
                ('medical_college_number', models.CharField(blank=True, max_length=60, null=True)),
                ('first_name', models.CharField(max_length=120)),
                ('last_name', models.CharField(max_length=120)),
                ('phone', models.CharField(blank=True, max_length=25, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('office_room', models.CharField(blank=True, max_length=40, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.PROTECT, to='core_organizations.organization')),
                ('specialty_main', models.ForeignKey(db_column='specialty_main_id', on_delete=django.db.models.deletion.PROTECT, to='doctors.specialty')),
                ('user', models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.RunSQL(
            sql=[
                "ALTER TABLE doctors_doctor ADD CONSTRAINT doctors_doctor_org_fk FOREIGN KEY (organization_id) REFERENCES core_organizations_organization(id)",
            ],
            reverse_sql=[
                "ALTER TABLE doctors_doctor DROP CONSTRAINT IF EXISTS doctors_doctor_org_fk",
            ],
        ),
        migrations.CreateModel(
            name='DoctorSpecialty',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('is_primary', models.BooleanField(default=False)),
                ('doctor', models.ForeignKey(db_column='doctor_id', on_delete=django.db.models.deletion.CASCADE, to='doctors.doctor')),
                ('specialty', models.ForeignKey(db_column='specialty_id', on_delete=django.db.models.deletion.CASCADE, to='doctors.specialty')),
            ],
            options={
                'unique_together': {('doctor', 'specialty')},
            },
        ),
        migrations.AddIndex(
            model_name='doctor',
            index=models.Index(fields=['organization'], name='doctor_org_idx'),
        ),
        migrations.AddIndex(
            model_name='doctor',
            index=models.Index(fields=['specialty_main'], name='doctor_specialty_idx'),
        ),
        migrations.AddIndex(
            model_name='doctor',
            index=models.Index(fields=['is_active'], name='doctor_is_active_idx'),
        ),
        migrations.AddIndex(
            model_name='doctor',
            index=models.Index(fields=['deleted_at'], name='doctor_deleted_at_idx'),
        ),
        migrations.AddConstraint(
            model_name='doctor',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('organization', 'cedula'), name='doctor_org_cedula_unique'),
        ),
        migrations.AddConstraint(
            model_name='doctor',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('organization', 'license_number'), name='doctor_org_license_unique'),
        ),
    ]
