# Generated by Django 4.2.15 on 2026-05-26 06:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecretaryDoctor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(db_column='doctor_id', on_delete=django.db.models.deletion.CASCADE, related_name='assigned_secretaries', to='doctors.doctor')),
                ('secretary', models.ForeignKey(db_column='secretary_id', on_delete=django.db.models.deletion.CASCADE, related_name='assigned_doctors', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
                'indexes': [models.Index(fields=['secretary'], name='sd_secretary_idx'), models.Index(fields=['doctor'], name='sd_doctor_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='secretarydoctor',
            constraint=models.UniqueConstraint(fields=('secretary', 'doctor'), name='secretary_doctor_unique'),
        ),
    ]
