# Generated by Django 3.2.25 on 2026-05-11 22:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core_organizations', '0002_convert_org_id_to_uuid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('doctors', '0002_convert_org_to_uuid'),
        ('patients', '0002_convert_org_to_uuid'),
        ('encounters', '0002_convert_org_to_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagingOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('order_number', models.CharField(max_length=50)),
                ('priority', models.CharField(choices=[('NORMAL', 'Normal'), ('URGENTE', 'Urgente')], default='NORMAL', max_length=20)),
                ('status', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('REALIZADA', 'Realizada'), ('EN_PROCESO', 'En proceso'), ('COMPLETADA', 'Completada'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=20)),
                ('clinical_indication', models.TextField()),
                ('ordered_at', models.DateTimeField(auto_now_add=True, db_column='ordered_at')),
                ('expected_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.PROTECT, related_name='imaging_orders_created', to=settings.AUTH_USER_MODEL)),
                ('doctor', models.ForeignKey(db_column='doctor_id', on_delete=django.db.models.deletion.PROTECT, to='doctors.doctor')),
                ('encounter', models.ForeignKey(db_column='encounter_id', on_delete=django.db.models.deletion.PROTECT, to='encounters.encounter')),
            ],
            options={
                'ordering': ['-ordered_at'],
            },
        ),
        migrations.CreateModel(
            name='ImagingTypeCatalog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=180)),
                ('modality', models.CharField(max_length=40)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ImagingReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('performed_at', models.DateTimeField(auto_now_add=True, db_column='performed_at')),
                ('findings', models.TextField()),
                ('impression', models.TextField()),
                ('recommendations', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('BORRADOR', 'Borrador'), ('FIRMADA', 'Firmada'), ('ANULADA', 'Anulada')], default='BORRADOR', max_length=20)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('content_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('signature_blob', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('imaging_order', models.ForeignKey(db_column='imaging_order_id', on_delete=django.db.models.deletion.CASCADE, to='imaging.imagingorder')),
                ('radiologist_user', models.ForeignKey(blank=True, db_column='radiologist_user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imaging_reports_radiologist', to=settings.AUTH_USER_MODEL)),
                ('technician_user', models.ForeignKey(db_column='technician_user_id', on_delete=django.db.models.deletion.PROTECT, related_name='imaging_reports_technician', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-performed_at'],
            },
        ),
        migrations.AddField(
            model_name='imagingorder',
            name='imaging_type',
            field=models.ForeignKey(db_column='imaging_type_id', on_delete=django.db.models.deletion.PROTECT, to='imaging.imagingtypecatalog'),
        ),
        migrations.AddField(
            model_name='imagingorder',
            name='organization',
            field=models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.PROTECT, to='core_organizations.organization'),
        ),
        migrations.AddField(
            model_name='imagingorder',
            name='patient',
            field=models.ForeignKey(db_column='patient_id', on_delete=django.db.models.deletion.PROTECT, to='patients.patient'),
        ),
        migrations.AddField(
            model_name='imagingorder',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='imaging_orders_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ImagingFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=255)),
                ('file_type', models.CharField(max_length=30)),
                ('storage_uri', models.TextField()),
                ('size_bytes', models.BigIntegerField()),
                ('sha256', models.CharField(max_length=64)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, db_column='uploaded_at')),
                ('imaging_order', models.ForeignKey(db_column='imaging_order_id', on_delete=django.db.models.deletion.CASCADE, to='imaging.imagingorder')),
                ('uploaded_by', models.ForeignKey(db_column='uploaded_by', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='imagingreport',
            index=models.Index(fields=['imaging_order'], name='img_report_order_idx'),
        ),
        migrations.AddIndex(
            model_name='imagingreport',
            index=models.Index(fields=['status'], name='img_report_status_idx'),
        ),
        migrations.AddIndex(
            model_name='imagingreport',
            index=models.Index(fields=['performed_at'], name='img_report_performed_idx'),
        ),
        migrations.AddConstraint(
            model_name='imagingreport',
            constraint=models.CheckConstraint(check=models.Q(('status__in', ['BORRADOR', 'FIRMADA', 'ANULADA'])), name='img_report_status_check'),
        ),
        migrations.AddConstraint(
            model_name='imagingreport',
            constraint=models.CheckConstraint(check=models.Q(models.Q(models.Q(('signed_at__isnull', False), ('status', 'FIRMADA'), ('radiologist_user__isnull', False)), ('status__ne', 'FIRMADA'), _connector='OR')), name='img_report_signed_check'),
        ),
        migrations.AddIndex(
            model_name='imagingorder',
            index=models.Index(fields=['encounter'], name='img_order_encounter_idx'),
        ),
        migrations.AddIndex(
            model_name='imagingorder',
            index=models.Index(fields=['patient'], name='img_order_patient_idx'),
        ),
        migrations.AddIndex(
            model_name='imagingorder',
            index=models.Index(fields=['status'], name='img_order_status_idx'),
        ),
        migrations.AddIndex(
            model_name='imagingorder',
            index=models.Index(fields=['ordered_at'], name='img_order_ordered_at_idx'),
        ),
        migrations.AddConstraint(
            model_name='imagingorder',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('organization', 'order_number'), name='img_order_org_number_unique'),
        ),
        migrations.AddConstraint(
            model_name='imagingorder',
            constraint=models.CheckConstraint(check=models.Q(('priority__in', ['NORMAL', 'URGENTE'])), name='img_order_priority_check'),
        ),
        migrations.AddConstraint(
            model_name='imagingorder',
            constraint=models.CheckConstraint(check=models.Q(('status__in', ['PENDIENTE', 'REALIZADA', 'EN_PROCESO', 'COMPLETADA', 'CANCELADA'])), name='img_order_status_check'),
        ),
        migrations.AddIndex(
            model_name='imagingfile',
            index=models.Index(fields=['imaging_order'], name='img_file_order_idx'),
        ),
        migrations.AddIndex(
            model_name='imagingfile',
            index=models.Index(fields=['uploaded_at'], name='img_file_uploaded_idx'),
        ),
    ]
